<?php

namespace app\components;

class Comp extends \yii\base\Component {
    public $message;
    public function init()
    {
        $this->message = 'Стандартное значение';
        parent::init(); // TODO: change the autogenerated stub
    }

    public function show($message)
    {
        $this->message = $message . ' строка';
        return $this->message;
    }
}